### PR TITLE
Html v2 - Proposal

### PR DESCRIPTION
**Pull request by RickBarretto**
* This proposal takes the #3 as reference, but removing all magic tricks and sugar syntax. This is a pure raw Html DSL, no magic tricks here.

### CODE REVIEW

**Comment by RickBarretto** [comment]
This may sound crazy, but the reason why I removed some tests is because I'll make this even more flexible.
Instead of determine what is right or wrong, I'll delegate this decision to the final user, by type inference. So, instead of delimite which type each element gets, this just gets and just produces the right output, simple like that.

So, if he is sending a dictionary as parameter, this MUST be a void element, period.
Also, this would reduce a lot the current amount of repetitive code, what reduces the chances of 
finding bugs, so, win-win.

**Comment by RickBarretto** [comment]
@drkameleon, can you help me to debug this? I have no idea what is going on...
image

**Comment by RickBarretto** [comment]
@drkameleon, and finished!
I hope you like it! 🙂

**Review by drkameleon — APPROVED** [review]
Pure awesomeness! 😉 ❤️

**Comment by drkameleon** [comment]
And... ready to merge! 🚀

**Pull request merged**
